import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Nunito } from "next/font/google";
import { Locale, routing } from "../../../i18n/route";
import LocaleSwitcher from "../_components/LocaleSwitcher";
import "./globals.css";

// Font Configuration
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

// Metadata for the Page
export const metadata: Metadata = {
  title: "Token Pocket",
  description: "Generated by create next app",
};

// Define Props for RootLayout
type RootLayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>; // Adjusted for async params
};

// Main Layout Component
export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params; // Await the resolution of params

  // Validate locale
  if (!routing.locales.includes(locale)) {
    throw new Error(`Invalid locale: ${locale}`);
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body className={`${nunito.className} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className="min-h-screen flex flex-col">
            {/* Header with Locale Switcher */}
            <header className="p-4 flex justify-end">
              <LocaleSwitcher />
            </header>
            {/* Main Content Area */}
            <main className="flex-1">{children}</main>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
